// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ApiClient;
using ApiClient.Models;
using Microsoft.Rest;

namespace ApiClient
{
    public static partial class OrdersExtensions
    {
        /// <param name='operations'>
        /// Reference to the ApiClient.IOrders.
        /// </param>
        public static IList<Order> GetOrders(this IOrders operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IOrders)s).GetOrdersAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ApiClient.IOrders.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Order>> GetOrdersAsync(this IOrders operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<ApiClient.Models.Order>> result = await operations.GetOrdersWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
